version: '3.7'

services:
  metrics_backend:
    container_name: metrics_backend
    restart: unless-stopped
    build: ./server
    expose:
      - 5000
    env_file: ./server/.env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=admin@miraclesti.com
      - VIRTUAL_PORT=5000
    depends_on:
      - metricsdb
  
  metrics_client:
    build: ./client
    container_name: metrics-client
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${WEB_HOST}
      - LETSENCRYPT_HOST=${WEB_HOST}
      - LETSENCRYPT_EMAIL=admin@miraclesti.com
      - VIRTUAL_PORT=3000
    volumes:
      - ./client/:/usr/src/app
    expose:
      - 80
      - 443
      - 3000
  metricsdb:
    container_name: metricsdb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: iot_metrics
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      
volumes:
  mongo_data: {}
  mongo_config: {}

networks:
  default:
    external: 
      name: nginx-proxy
