version: '3.7'

services:
  seefs_backend:
    container_name: seefs_backend
    restart: unless-stopped
    build: ./backend
    ports:
      - '7000:7000'
    environment:
      - NODE_ENV=production
    # networks:
    #   - internal
    depends_on:
      - seefsdb

  seefs_frontend:
    container_name: seefs_frontend
    restart: unless-stopped
    build: ./frontend
    environment:
      - NODE_PATH=/app/src
      - VIRTUAL_PORT=3005
      - VIRTUAL_HOST=seefs.miraclesti.com
      - LETSENCRYPT_HOST=seefs.miraclesti.com
      - LETSENCRYPT_EMAIL=admin@miraclesti.com
    # expose:
    #   - 80
    #   - 443
    #   - 3000
    ports: 
    - '3005:80'
    depends_on:
      - seefs_backend
    # networks:
    #   - internal

  seefsdb:
    container_name: seefsdb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: seefs
    ports:
      - '27017:27017'
    volumes:
      - seefs_data:/data/db
      - seefs_config:/data/configdb

networks:
  default:
    external: 
      name: nginx-proxy

volumes:
  seefs_data: {}
  seefs_config: {}